"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from cryptography.fernet import Fernet
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6fde&z+d=+ekku5mqdh*-qnif=f7mogbc*&sn34wfi916hjba('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#
# ==============================
# CMDB_FERNET_KEY 说明
# ==============================
# 用途：
#   该密钥用于加密/解密主机 root 密码（Fernet 对称加密主密钥）。
#   Fernet 的 key 必须是“32 字节原始 key 的 urlsafe-base64 编码”（通常长度 44，末尾带 '='）。
#   生产环境必须通过环境变量注入，严禁把真实密钥写进代码仓库。
#
# 本地开发测试：
#   若未设置环境变量 CMDB_FERNET_KEY，则使用下面的 DEV 默认值（仅用于本地跑通）。
#   ⚠️ 注意：更换该 key 会导致历史密文无法解密。
# ==============================
CMDB_FERNET_KEY = os.getenv(
    "CMDB_FERNET_KEY",
    "u4pQkK8x5d8m8mG7g1qv0k3v8l2jvQm0j2s8cQf3p2A=",  # DEV ONLY
)


# 校验
try:
    Fernet(CMDB_FERNET_KEY.encode("utf-8"))
except Exception as e:
    raise RuntimeError(
        "CMDB_FERNET_KEY 非法：必须为 Fernet 规范的 urlsafe-base64 key（可用 Fernet.generate_key() 生成）"
    ) from e


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.cmdb',
    'apps.ops',
    'apps.security',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'common.drf.RequestTimingMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydb',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': 5432
    }
}

# ==============================
# Celery 配置
# ==============================

# 使用 Redis 作为 broker（需要本地已启动 redis）
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"

# 时区配置
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = False

# 并发（开发环境）
CELERY_WORKER_CONCURRENCY = 4

# 序列化格式
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"

CELERY_BEAT_SCHEDULE = {
    # 定时任务：每 8 小时执行一次密码轮换
    "rotate-password-every-8-hours": {
        "task": "apps.security.tasks.rotate_passwords_batch",
        "schedule": crontab(minute=0, hour="*/8"),
        # "schedule": crontab(minute="*/2"),
    },
    # 按城市和机房维度统计主机数量, 每天00:00:00
    "daily-host-stat": {
        "task": "apps.cmdb.tasks.daily_host_stat",
        "schedule": crontab(minute=0, hour=0),
        # "schedule": crontab(minute="*/3"),
    },
}


REST_FRAMEWORK = {
    # 分页
    "DEFAULT_PAGINATION_CLASS": "common.drf.CountDataPagination",
    "PAGE_SIZE": 10,

    # 统一返回格式
    "DEFAULT_RENDERER_CLASSES": (
        "common.drf.MessageDataJSONRenderer",
    ),
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(name)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'when': 'midnight',
            'backupCount': 7,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
